processors:
    - '@mapbox/stylelint-processor-arbitrary-tags':
          fileFilterRegex: [/\.vue$/]
extends:
    - stylelint-config-standard
    - stylelint-config-recommended-vue
plugins:
    - stylelint-use-nesting
rules:
    color-function-notation: modern
    selector-nested-pattern: '&'
    no-empty-first-line: null
    no-empty-source: null
    csstools/use-nesting: true
